image: node:10

stages:
  - build
  - lint
  - test
  - package

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script: 
    - npm run lint
  only:
    - branches

testing:
  stage: test
  script: 
    - npm test
  only:
    - branches

docker:
  services:
   - docker:dind
  stage: package
  image: docker:git
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_TAG: $CI_COMMIT_REF_NAME
  before_script:
   - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CONTAINER_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CONTAINER_TAG
  only:
    refs:
      - qa
      - master
